const $ = id => document.getElementById(id);
const state = {
  expressions: [], fullbodyId: null, fullbodyStandalone: null, selected: null, activeLayer: null, sortId: null,
  fontFamily: 'system-ui', fontName: '系统默认', fontData: null,
  layout: {nameX:70,nameY:80,fullX:150,fullY:120,fullBaseW:380,fullScale:100,groupX:520,groupY:60},
  layoutSet: false, drag: null
};
const controls = ['canvasW','bgColor','transparent','characterName','nameColor','nameSize','subtitle','subtitleColor','subtitleSide','subtitleSize','labelSize','labelPrefix','labelColor','labelStrokeColor','columns','colGap','rowGap','showLabels','showLabelBg','cropX','cropY','fullScale','groupX','groupY','cellW','cellH','diffBgColor','exportScale'];
const val = id => $(id).type === 'checkbox' ? $(id).checked : $(id).type === 'number' || $(id).type === 'range' ? Number($(id).value) : $(id).value;
function readControls(){const c={};controls.forEach(id=>c[id]=val(id));return c}
function setControls(c){controls.forEach(id=>{if(c[id]===undefined)return;$(id).type==='checkbox'?$(id).checked=c[id]:$(id).value=c[id]});syncRangeLabels()}
function syncRangeLabels(){['cropX','cropY','groupX','groupY','cellW','cellH'].forEach(id=>$(id+'Value').textContent=$(id).value);$('fullScaleValue').textContent=$('fullScale').value+'%'}
function syncLayoutInputs(){const l=state.layout;['groupX','groupY'].forEach(id=>$(id).value=Math.round(l[id]));$('fullScale').value=Math.round(l.fullScale||100);syncRangeLabels()}
function uid(){return crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random())}
function loadImage(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>resolve({fileName:file.name,data:r.result,img});img.onerror=reject;img.src=r.result};r.onerror=reject;r.readAsDataURL(file)})}
function imageFromData(data){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src=data})}
function stripName(name){return name.replace(/\.[^.]+$/,'').replace(/^\d+[_\- ]*/,'')||'差分'}
function chooseDefaultFullbody(){return state.expressions.find(x=>/默认|普通|通常|01|default/i.test((x.name||'')+(x.fileName||'')))||state.expressions[0]||null}
function fullbody(){return state.fullbodyStandalone||state.expressions.find(x=>x.id===state.fullbodyId)||null}
function bodyAspect(){const x=fullbody();return x&&x.img.width?x.img.height/x.img.width:1.7}
function fullRect(){const l=state.layout,w=(l.fullBaseW||380)*(l.fullScale||100)/100;return {x:l.fullX,y:l.fullY,w,h:w*bodyAspect()}}
function groupRect(){const c=readControls(),cols=Math.max(1,c.columns),visible=state.expressions.filter(x=>x.visible),rows=Math.ceil(visible.length/cols)||1;return {x:state.layout.groupX,y:state.layout.groupY,w:cols*c.cellW+Math.max(0,cols-1)*c.colGap,h:rows*c.cellH+Math.max(0,rows-1)*c.rowGap}}
function resetLayout(){const c=readControls(),w=Math.max(900,c.canvasW),cellW=c.cellW||240,groupW=Math.max(1,c.columns)*cellW+Math.max(0,c.columns-1)*c.colGap;state.layout={nameX:70,nameY:80,fullX:150,fullY:120,fullBaseW:Math.min(380,Math.max(240,w*.23)),fullScale:100,groupX:Math.max(40,w-60-groupW),groupY:60};state.layoutSet=true;syncLayoutInputs()}
async function addExpressions(files){const incoming=[...files].filter(f=>f.type.startsWith('image/'));for(const file of incoming){const x=await loadImage(file);state.expressions.push({id:uid(),fileName:file.name,name:stripName(file.name),data:x.data,img:x.img,dx:0,dy:0,zoom:1,visible:true})}state.expressions.sort((a,b)=>(a.fileName||'').localeCompare(b.fileName||'','zh'));if(!state.fullbodyId&&!state.fullbodyStandalone){const x=chooseDefaultFullbody();state.fullbodyId=x?.id||null;resetLayout()}state.selected=state.selected||state.expressions[0]?.id||null;renderAll()}
function currentSelected(){return state.expressions.find(x=>x.id===state.selected)}
function setFullbody(id){state.fullbodyStandalone=null;state.fullbodyId=id||null;renderAll()}
function handleStandaloneFullbody(file){loadImage(file).then(x=>{state.fullbodyStandalone={data:x.data,img:x.img,name:file.name};state.fullbodyId=null;if(!state.layoutSet)resetLayout();renderAll()})}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function installFont(data,name){return new Promise((resolve,reject)=>{const face=new FontFace('UploadedLocalFont',`url(${data})`);face.load().then(loaded=>{document.fonts.add(loaded);state.fontFamily='UploadedLocalFont';state.fontName=name||'本地字体';state.fontData=data;$('fontName').textContent='当前字体：'+state.fontName;renderAll();resolve()}).catch(reject)})}
function fitImage(ctx,img,x,y,w,h){const s=Math.min(w/img.width,h/img.height),dw=img.width*s,dh=img.height*s;ctx.drawImage(img,x+(w-dw)/2,y+(h-dh)/2,dw,dh)}
function drawVerticalText(ctx,text,x,y,size,color){ctx.save();ctx.fillStyle=color||'#202733';ctx.font=`700 ${size}px "${state.fontFamily}"`;ctx.textAlign='center';ctx.textBaseline='top';[...text].forEach((ch,i)=>ctx.fillText(ch,x,y+i*size*1.12));ctx.restore()}
function cropIntoBox(ctx,x,c,box){const img=x.img,cropX=img.width*c.cropX/100,cropY=img.height*c.cropY/100,cropW=img.width*44/100,cropH=img.height*30/100,z=x.zoom||1,aspect=box.w/box.h;let sw=cropW/z,sh=cropH/z;if(sw/sh>aspect)sw=sh*aspect;else sh=sw/aspect;const cx=cropX+cropW/2+cropW*(x.dx||0)/100,cy=cropY+cropH/2+cropH*(x.dy||0)/100;let sx=cx-sw/2,sy=cy-sh/2;sx=Math.max(0,Math.min(img.width-sw,sx));sy=Math.max(0,Math.min(img.height-sh,sy));ctx.drawImage(img,sx,sy,sw,sh,box.x,box.y,box.w,box.h)}
function labelBox(ctx,text,x,y,w,h,size,showBg,textColor,strokeColor){ctx.save();ctx.font=`650 ${size}px "${state.fontFamily}"`;const tw=Math.min(w-8,ctx.measureText(text).width+14),th=Math.min(h-8,size+8),cx=x+w-tw/2-5,cy=y+h-th/2-5;if(showBg){ctx.fillStyle='#ffffffdd';ctx.fillRect(x+w-tw-5,y+h-th-5,tw,th)}ctx.textAlign='center';ctx.textBaseline='middle';ctx.lineWidth=4;ctx.strokeStyle=strokeColor||'#fff';ctx.strokeText(text,cx,cy);ctx.fillStyle=textColor||'#202733';ctx.fillText(text,cx,cy);ctx.restore()}
function subtitleX(nameX,nameSize,side,subtitleSize){return side==='left'?nameX-nameSize/2-subtitleSize/2-14:nameX+nameSize/2+subtitleSize/2+14}
function nameBlockRect(nameX,nameY,nameSize,subtitle,subtitleSize,side){const nameH=Math.max(1,[...readControls().characterName].length)*nameSize*1.12+8,items=[{x:nameX-nameSize/2-8,y:nameY-6,w:nameSize+16,h:nameH}];if(subtitle){const sx=subtitleX(nameX,nameSize,side,subtitleSize),sh=Math.max(1,[...subtitle].length)*subtitleSize*1.12+8;items.push({x:sx-subtitleSize/2-8,y:nameY-6,w:subtitleSize+16,h:sh})}const left=Math.min(...items.map(x=>x.x)),top=Math.min(...items.map(x=>x.y)),right=Math.max(...items.map(x=>x.x+x.w)),bottom=Math.max(...items.map(x=>x.y+x.h));return {x:left,y:top,w:right-left,h:bottom-top}}
function selectionRect(layer){const c=readControls(),l=state.layout;if(layer==='name')return nameBlockRect(l.nameX,l.nameY,c.nameSize,c.subtitle,c.subtitleSize,c.subtitleSide);if(layer==='fullbody')return fullRect();return groupRect()}
function drawHandles(ctx,r){const s=9;ctx.fillStyle='#fff';ctx.strokeStyle='#5267d9';ctx.lineWidth=2;[[r.x,r.y],[r.x+r.w,r.y],[r.x,r.y+r.h],[r.x+r.w,r.y+r.h],[r.x+r.w/2,r.y],[r.x+r.w/2,r.y+r.h],[r.x,r.y+r.h/2],[r.x+r.w,r.y+r.h/2]].forEach(([x,y])=>{ctx.fillRect(x-s/2,y-s/2,s,s);ctx.strokeRect(x-s/2,y-s/2,s,s)})}
const canvas=$('preview'),stage=$('canvasStage'),overlay=$('selectionOverlay'),canvasWrap=stage.parentElement;
function clearSelection(){state.activeLayer=null;state.selected=null;renderList();updateSelectedUI();draw()}
function syncCanvasStage(){const wrap=stage.parentElement,available=Math.max(120,wrap.clientWidth-40),scale=Math.min(1,available/canvas.width);stage.style.width=`${Math.round(canvas.width*scale)}px`;stage.style.height=`${Math.round(canvas.height*scale)}px`}
function syncSelectionOverlay(){if(!state.activeLayer||!['name','fullbody'].includes(state.activeLayer)){overlay.style.display='none';overlay.innerHTML='';overlay.dataset.layer='';return}const r=selectionRect(state.activeLayer),scale=stage.clientWidth/canvas.width;overlay.style.display='block';overlay.style.left='0';overlay.style.top='0';if(overlay.dataset.layer!==state.activeLayer||overlay.children.length!==4){overlay.innerHTML=['nw','ne','sw','se'].map(h=>`<button class="selection-handle ${h}" data-handle="${h}" aria-label="${h}"></button>`).join('');overlay.dataset.layer=state.activeLayer}overlay.querySelectorAll('.selection-handle').forEach(el=>{const h=el.dataset.handle, x=h.includes('w')?r.x:r.x+r.w, y=h.includes('n')?r.y:r.y+r.h;el.style.left=`${x*scale}px`;el.style.top=`${y*scale}px`})}
function draw(target=canvas,scale=1,includeSelection=true){const c=readControls();if(!state.layoutSet&&state.expressions.length)resetLayout();const l=state.layout,visible=state.expressions.filter(x=>x.visible),cols=Math.max(1,c.columns),rows=Math.ceil(visible.length/cols)||1,g=groupRect(),body=fullRect(),nameRect=nameBlockRect(l.nameX,l.nameY,c.nameSize,c.subtitle,c.subtitleSize,c.subtitleSide),w=Math.ceil(Math.max(900,c.canvasW)),h=Math.ceil(Math.max(700,g.y+g.h+60,body.y+body.h+60,nameRect.y+nameRect.h+60));target.width=Math.max(1,Math.round(w*scale));target.height=Math.max(1,Math.round(h*scale));const ctx=target.getContext('2d');ctx.setTransform(scale,0,0,scale,0,0);ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.clearRect(0,0,w,h);if(!c.transparent){ctx.fillStyle=c.bgColor;ctx.fillRect(0,0,w,h)}
  drawVerticalText(ctx,c.characterName,l.nameX,l.nameY,c.nameSize,c.nameColor);if(c.subtitle){drawVerticalText(ctx,c.subtitle,subtitleX(l.nameX,c.nameSize,c.subtitleSide,c.subtitleSize),l.nameY,c.subtitleSize,c.subtitleColor)}
  const bodyImage=fullbody();if(bodyImage){ctx.save();ctx.beginPath();ctx.rect(body.x,body.y,body.w,body.h);ctx.clip();ctx.drawImage(bodyImage.img,body.x,body.y,body.w,body.h);ctx.restore()}
  visible.forEach((x,i)=>{const col=i%cols,row=Math.floor(i/cols),box={x:g.x+col*(c.cellW+c.colGap),y:g.y+row*(c.cellH+c.rowGap),w:c.cellW,h:c.cellH};ctx.fillStyle=c.diffBgColor||'#f0f2f5';ctx.fillRect(box.x,box.y,box.w,box.h);cropIntoBox(ctx,x,c,box);if(c.showLabels)labelBox(ctx,c.labelPrefix+x.name,box.x,box.y,box.w,box.h,c.labelSize,c.showLabelBg,c.labelColor,c.labelStrokeColor);if(includeSelection&&x.id===state.selected){ctx.strokeStyle='#5267d9';ctx.lineWidth=3;ctx.strokeRect(box.x-2,box.y-2,box.w+4,box.h+4)}});
  if(includeSelection&&(state.activeLayer==='name'||state.activeLayer==='fullbody')){const r=selectionRect(state.activeLayer);ctx.strokeStyle='#5267d9';ctx.lineWidth=2;ctx.strokeRect(r.x,r.y,r.w,r.h)}else if(includeSelection&&state.activeLayer==='group'){ctx.strokeStyle='#5267d9';ctx.lineWidth=2;ctx.setLineDash([8,6]);ctx.strokeRect(g.x,g.y,g.w,g.h);ctx.setLineDash([])}
  if(target===canvas){syncCanvasStage();syncSelectionOverlay();$('sizeText').textContent=`${w} × ${h} px`}return {w,h}}
function renderFullbodySelect(){const select=$('fullbodySelect'),old=state.fullbodyId;select.innerHTML='<option value="">未选择</option>';state.expressions.forEach(x=>{const o=document.createElement('option');o.value=x.id;o.textContent=x.name;select.appendChild(o)});select.value=state.fullbodyId||'';if(old&&!select.value){state.fullbodyId=state.expressions[0]?.id||null;select.value=state.fullbodyId||''}}
function updateSelectedUI(){const x=currentSelected(),p=$('selectionPanel');p.style.display=x?'block':'none';if(x){$('selectedX').value=x.dx;$('selectedY').value=x.dy;$('selectedZoom').value=x.zoom}}
function renderList(){const box=$('expressionList');box.innerHTML='';$('count').textContent=state.expressions.length?`(${state.expressions.length})`:'';state.expressions.forEach(x=>{const el=document.createElement('div');el.className='expr'+(x.id===state.selected?' selected':'');el.draggable=true;el.innerHTML=`<img src="${x.data}" alt=""><div class="name"><input value="${escapeHtml(x.name)}"><div class="sub">${x.img.width} × ${x.img.height}${x.id===state.fullbodyId?' · 全身':''}</div></div><button class="icon-btn" title="移除">×</button>`;el.onclick=()=>{state.selected=x.id;renderAll()};const input=el.querySelector('input');input.onclick=e=>e.stopPropagation();input.ondragstart=e=>e.preventDefault();input.oninput=e=>{x.name=e.target.value;draw();renderFullbodySelect()};el.querySelector('.icon-btn').onclick=e=>{e.stopPropagation();state.expressions=state.expressions.filter(y=>y!==x);if(state.fullbodyId===x.id)state.fullbodyId=chooseDefaultFullbody()?.id||null;if(state.selected===x.id)state.selected=state.expressions[0]?.id||null;renderAll()};el.ondragstart=e=>{if(e.target.closest('.name input,.icon-btn')){e.preventDefault();return}state.sortId=x.id;e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',x.id);el.classList.add('drag-source')};el.ondragend=()=>{state.sortId=null;el.classList.remove('drag-source');box.querySelectorAll('.drag-over').forEach(y=>y.classList.remove('drag-over'))};el.ondragover=e=>{e.preventDefault();if(state.sortId&&state.sortId!==x.id)el.classList.add('drag-over')};el.ondragleave=()=>el.classList.remove('drag-over');el.ondrop=e=>{e.preventDefault();el.classList.remove('drag-over');if(!state.sortId||state.sortId===x.id)return;const from=state.expressions.findIndex(y=>y.id===state.sortId),to=state.expressions.findIndex(y=>y.id===x.id);const [item]=state.expressions.splice(from,1);state.expressions.splice(to,0,item);state.sortId=null;renderAll()};box.appendChild(el)})}
function renderAll(){const has=state.expressions.length>0||!!state.fullbodyStandalone;$('emptyState').style.display=has?'none':'flex';$('statusText').textContent=has?`已载入 ${state.expressions.length} 张图片`:'等待导入图片';syncLayoutInputs();draw();renderFullbodySelect();renderList();updateSelectedUI()}
const imageResizer=typeof window.pica==='function'?window.pica({features:['js','wasm']}):null;
async function resizeExportCanvas(source,width,height){const out=document.createElement('canvas');out.width=width;out.height=height;if(imageResizer){await imageResizer.resize(source,out,{filter:'mks2013',unsharpAmount:0})}else{const ctx=out.getContext('2d');ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage(source,0,0,source.width,source.height,0,0,width,height)}return out}
async function renderExportCanvas(scale,size){const baseScale=scale===1?2:scale,master=document.createElement('canvas');draw(master,baseScale*2,false);let out=await resizeExportCanvas(master,Math.round(size.w*baseScale),Math.round(size.h*baseScale));if(scale===1)out=await resizeExportCanvas(out,size.w,size.h);return out}
async function exportPng(){if(!state.expressions.length)return alert('请先导入立绘');try{const c=readControls(),k=c.exportScale,size=draw(),out=await renderExportCanvas(k,size),a=document.createElement('a');a.download=(c.characterName||'差分平铺')+'.png';a.href=out.toDataURL('image/png');a.click()}catch(err){console.error(err);alert('图片导出失败，请重试')}}
function projectData(){return {version:4,controls:readControls(),layout:state.layout,font:{data:state.fontData,name:state.fontName},fullbodyIndex:state.expressions.findIndex(x=>x.id===state.fullbodyId),fullbodyStandalone:state.fullbodyStandalone?{data:state.fullbodyStandalone.data,name:state.fullbodyStandalone.name}:null,expressions:state.expressions.map((x,order)=>({data:x.data,fileName:x.fileName,name:x.name,dx:x.dx,dy:x.dy,zoom:x.zoom,visible:x.visible,order}))}}
async function loadProjectData(p){setControls(p.controls||{});if(p.controls&&!p.controls.cellW)setControls({cellW:p.controls.cellSize||240,cellH:p.controls.cellSize||220});state.expressions=[];for(const x of p.expressions||[]){state.expressions.push({id:uid(),...x,img:await imageFromData(x.data)})}state.expressions.sort((a,b)=>(Number.isFinite(a.order)&&Number.isFinite(b.order)?a.order-b.order:0));const index=Number.isInteger(p.fullbodyIndex)?p.fullbodyIndex:0;state.fullbodyStandalone=p.fullbodyStandalone?{data:p.fullbodyStandalone.data,name:p.fullbodyStandalone.name,img:await imageFromData(p.fullbodyStandalone.data)}:null;state.fullbodyId=state.fullbodyStandalone?null:(state.expressions[index]?.id||null);state.layout={...state.layout,...(p.layout||{})};if(!state.layout.fullBaseW)state.layout.fullBaseW=380;if(!state.layout.fullScale)state.layout.fullScale=100;state.layoutSet=true;state.selected=state.expressions[0]?.id||null;if(p.font?.data)await installFont(p.font.data,p.font.name);renderAll()}
function point(e){const r=$('preview').getBoundingClientRect();return {x:(e.clientX-r.left)*$('preview').width/r.width,y:(e.clientY-r.top)*$('preview').height/r.height}}
function handleAt(p,r){const t=18,hs={nw:[r.x,r.y],ne:[r.x+r.w,r.y],sw:[r.x,r.y+r.h],se:[r.x+r.w,r.y+r.h]};for(const [name,[x,y]] of Object.entries(hs))if(Math.abs(p.x-x)<=t&&Math.abs(p.y-y)<=t)return name;return null}
function clamp(n,min,max){return Math.max(min,Math.min(max,n))}
function resizeName(d,p){const c=readControls(),r=d.originRect,side=d.handle,signX=side.includes('w')?-1:1,signY=side.includes('n')?-1:1,delta=(signX*(p.x-d.start.x)+signY*(p.y-d.start.y))/2,scale=clamp(1+delta/Math.max(r.w,r.h),.25,3),nameSize=clamp(d.originSize.name*scale,12,240),subtitleSize=clamp(d.originSize.subtitle*scale,8,180),target=nameBlockRect(0,0,nameSize,c.subtitle,subtitleSize,c.subtitleSide),anchorX=side.includes('w')?r.x+r.w:r.x,anchorY=side.includes('n')?r.y+r.h:r.y,left=side.includes('w')?anchorX-target.w:anchorX,top=side.includes('n')?anchorY-target.h:anchorY;$('nameSize').value=Math.round(nameSize);$('subtitleSize').value=Math.round(subtitleSize);state.layout.nameX=left-target.x;state.layout.nameY=top-target.y}
function resizeFullbody(d,p){const r=d.originRect,aspect=bodyAspect(),side=d.handle,signX=side.includes('w')?-1:1,signY=side.includes('n')?-1:1,delta=(signX*(p.x-d.start.x)+signY*(p.y-d.start.y))/2,w=clamp(r.w+delta,40,(state.layout.fullBaseW||380)*2.2),h=w*aspect,anchorX=side.includes('w')?r.x+r.w:r.x,anchorY=side.includes('n')?r.y+r.h:r.y;state.layout.fullScale=clamp(w/(state.layout.fullBaseW||380)*100,20,220);state.layout.fullX=side.includes('w')?anchorX-w:anchorX;state.layout.fullY=side.includes('n')?anchorY-h:anchorY}
function cellAt(p){const c=readControls(),g=groupRect(),visible=state.expressions.filter(x=>x.visible),cols=Math.max(1,c.columns);for(let i=0;i<visible.length;i++){const x=visible[i],box={x:g.x+(i%cols)*(c.cellW+c.colGap),y:g.y+Math.floor(i/cols)*(c.cellH+c.rowGap),w:c.cellW,h:c.cellH};if(p.x>=box.x&&p.x<=box.x+box.w&&p.y>=box.y&&p.y<=box.y+box.h)return {x,box,label:c.showLabels&&p.y>box.y+box.h-c.labelSize-14}}return null}
function hitLayer(p){const n=selectionRect('name'),b=selectionRect('fullbody'),g=groupRect();if(p.x>=n.x&&p.x<=n.x+n.w&&p.y>=n.y&&p.y<=n.y+n.h)return 'name';if(p.x>=b.x&&p.x<=b.x+b.w&&p.y>=b.y&&p.y<=b.y+b.h)return 'fullbody';if(p.x>=g.x&&p.x<=g.x+g.w&&p.y>=g.y&&p.y<=g.y+g.h)return 'group';return null}
overlay.addEventListener('pointerdown',e=>{const handle=e.target.closest('.selection-handle');if(!handle||!state.activeLayer)return;const layer=state.activeLayer,r=selectionRect(layer),c=readControls(),l=state.layout;state.drag={layer,mode:'resize',source:'overlay',handle:handle.dataset.handle,start:point(e),origin:{x:layer==='name'?l.nameX:l.fullX,y:layer==='name'?l.nameY:l.fullY},originSize:layer==='name'?{name:c.nameSize,subtitle:c.subtitleSize}:l.fullScale,originRect:r,moved:false};handle.setPointerCapture(e.pointerId);e.preventDefault();e.stopPropagation()});
overlay.addEventListener('pointermove',e=>{const d=state.drag;if(!d||d.source!=='overlay')return;const p=point(e);d.moved=true;if(d.layer==='name')resizeName(d,p);else resizeFullbody(d,p);syncLayoutInputs();draw();e.preventDefault()});
overlay.addEventListener('pointerup',e=>{if(state.drag?.source!=='overlay')return;state.drag=null;canvas.classList.remove('dragging');draw();e.preventDefault()});
overlay.addEventListener('pointercancel',e=>{if(state.drag?.source!=='overlay')return;state.drag=null;canvas.classList.remove('dragging');draw();e.preventDefault()});
canvas.addEventListener('pointerdown',e=>{const p=point(e),layer=hitLayer(p),r=layer?selectionRect(layer):null,handle=layer&&(['name','fullbody'].includes(layer))?handleAt(p,r):null,c=readControls(),l=state.layout;if(handle){state.activeLayer=layer;state.drag={layer,mode:'resize',handle,start:p,origin:{x:layer==='name'?l.nameX:l.fullX,y:layer==='name'?l.nameY:l.fullY},originSize:layer==='name'?{name:c.nameSize,subtitle:c.subtitleSize}:l.fullScale,originRect:r,moved:false};canvas.classList.add('dragging');canvas.setPointerCapture(e.pointerId);draw();return}const cell=cellAt(p);if(cell?.label){state.selected=cell.x.id;renderList();updateSelectedUI();state.drag={layer:'label',start:p,moved:false,x:cell.x};canvas.setPointerCapture(e.pointerId);return}if(!layer){state.activeLayer=null;state.selected=null;renderList();updateSelectedUI();draw();return}state.activeLayer=layer;state.drag={layer,mode:'move',handle:null,start:p,origin:{x:layer==='name'?l.nameX:layer==='fullbody'?l.fullX:l.groupX,y:layer==='name'?l.nameY:layer==='fullbody'?l.fullY:l.groupY},originSize:layer==='name'?{name:c.nameSize,subtitle:c.subtitleSize}:layer==='fullbody'?l.fullScale:null,originRect:r,moved:false};canvas.classList.add('dragging');canvas.setPointerCapture(e.pointerId);draw()});
canvas.addEventListener('pointermove',e=>{const d=state.drag;if(!d||d.layer==='label')return;const p=point(e),dx=p.x-d.start.x,dy=p.y-d.start.y;if(Math.abs(dx)+Math.abs(dy)>3)d.moved=true;const l=state.layout;if(d.mode==='move'){if(d.layer==='name'){l.nameX=d.origin.x+dx;l.nameY=d.origin.y+dy}else if(d.layer==='fullbody'){l.fullX=d.origin.x+dx;l.fullY=d.origin.y+dy}else{l.groupX=d.origin.x+dx;l.groupY=d.origin.y+dy}}else if(d.layer==='name')resizeName(d,p);else if(d.layer==='fullbody')resizeFullbody(d,p);syncLayoutInputs();draw()});
canvas.addEventListener('pointerup',e=>{const d=state.drag;if(!d)return;const p=point(e);if(d.layer==='label'&&!d.moved){const value=prompt('修改差分名称',d.x.name);if(value!==null){d.x.name=value;renderAll()}}state.drag=null;canvas.classList.remove('dragging');draw()});
controls.forEach(id=>$(id).addEventListener('input',()=>{if(id==='groupX'||id==='groupY')state.layout[id]=val(id);if(id==='fullScale')state.layout.fullScale=val(id);syncRangeLabels();draw()}));
$('imageFiles').onchange=e=>addExpressions(e.target.files);$('fullbodyFile').onchange=e=>{const file=e.target.files[0];if(file)handleStandaloneFullbody(file)};$('fullbodySelect').onchange=e=>setFullbody(e.target.value);$('exportPng').onclick=exportPng;
$('fontFile').onchange=e=>{const file=e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>installFont(r.result,file.name).catch(()=>alert('字体读取失败'));r.readAsDataURL(file)};
$('resetFont').onclick=()=>{state.fontFamily='system-ui';state.fontName='系统默认';state.fontData=null;$('fontFile').value='';$('fontName').textContent='当前字体：系统默认';renderAll()};
$('resetColors').onclick=()=>{setControls({bgColor:'#ffffff',transparent:false,nameColor:'#202733',subtitleColor:'#202733',labelColor:'#202733',labelStrokeColor:'#ffffff',diffBgColor:'#f0f2f5'});draw()};
$('newProject').onclick=()=>{if(confirm('清空当前工程？')){state.expressions=[];state.fullbodyId=null;state.fullbodyStandalone=null;state.selected=null;state.layoutSet=false;state.fontFamily='system-ui';state.fontName='系统默认';state.fontData=null;$('fontName').textContent='当前字体：系统默认';renderAll()}};
$('saveProject').onclick=()=>{const b=new Blob([JSON.stringify(projectData())],{type:'application/json'}),a=document.createElement('a');a.download='差分平铺工程.json';a.href=URL.createObjectURL(b);a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};
$('loadProject').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>loadProjectData(JSON.parse(r.result)).catch(()=>alert('工程文件读取失败'));r.readAsText(f)};
window.addEventListener('resize',()=>{syncCanvasStage();syncSelectionOverlay()});
['selectedX','selectedY','selectedZoom'].forEach(id=>$(id).oninput=()=>{const x=currentSelected();if(!x)return;x.dx=Number($('selectedX').value)||0;x.dy=Number($('selectedY').value)||0;x.zoom=Number($('selectedZoom').value)||1;draw()});$('resetSelected').onclick=()=>{const x=currentSelected();if(!x)return;x.dx=x.dy=0;x.zoom=1;updateSelectedUI();draw()};
canvasWrap.addEventListener('pointerdown',e=>{if(e.target===canvasWrap)clearSelection()});
const dz=$('dropZone');['dragenter','dragover'].forEach(e=>dz.addEventListener(e,x=>{x.preventDefault();dz.classList.add('over')}));['dragleave','drop'].forEach(e=>dz.addEventListener(e,x=>{x.preventDefault();dz.classList.remove('over')}));dz.addEventListener('drop',e=>addExpressions(e.dataTransfer.files));
function resetStartupText(){ $('characterName').value='角色姓名'; $('subtitle').value=''; draw() }
window.addEventListener('pageshow',resetStartupText);
resetStartupText();
renderAll();
